/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index'
      },
      items: ['Getting Started/Overview', 'Getting Started/Installation', 'Getting Started/Usage']
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index'
      },
      items: ['Components/Button','Components/AnonymousSigninButton','Components/SignoutButton', 'Components/FormControl']
    },
    {
      type: 'category',
      label: 'Hooks',
      link: {
        type: 'generated-index'
      },
      items: ['Hooks/useAuthenticatedUser']
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index'
      },
      items: ['Guides/signup with email' , 'Guides/signin with email']
    }
  ]
}

module.exports = sidebars
